DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;

CREATE TABLE artists(
  ID SERIAL8 PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE albums(
  ID SERIAL8 PRIMARY KEY,
  name VARCHAR(255),
  genre VARCHAR(255),
  artist_id INT8 REFERENCES artists(id) ON DELETE
  CASCADE
);
